application.security.refreshToken.secret : refreshSecret
application.security.token.secret: secret
server:
  port: 8080

spring:
  application:
    name: pfr-backend
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: dbPFR
      port: 27017
      host: localhost
      auto-index-creation: true

